### ISSUE TITLE
Media query unit question

### ISSUE THREAD

**Issue by mrmrs** [suitcss/theme#2]
Suitcss has been pretty fascinating to watch evolve over the past 18+ months. Would love to hear your thoughts on why you're using px units instead of ems for media queries. Thanks!

**Comment by simonsmith** [comment]
I think this post gives a nice overview of why you may want to use `px` and not `em` - https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/
